# Generated by Django 4.2.11 on 2024-04-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monsters', '0008_buff_skill_monster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buff_Skill_Monster',
        ),
    ]
