# Generated by Django 4.2.11 on 2024-04-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Builds',
        ),
    ]
