[uwsgi]
# Plugin settings
plugin-dir = /usr/local/src/uwsgi-2.0.18
plugins = python38

# Django settings
module = TavernofSoul.wsgi_ktos:application
chdir = /home/ubuntu/TavernofSoul/TavernofSoul
pythonpath = /home/ubuntu/TavernofSoul/TavernofSoul
virtualenv = /home/ubuntu/TavernofSoul/TavernofSoul/ktos/3.8
env = DJANGO_SETTINGS_MODULE=TavernofSoul.settings_ktos
master = true
processes = 4
threads = 2
vacuum = true
die-on-term = true
max-requests = 1000
harakiri = 60
pidfile = /home/ubuntu/TavernofSoul/TavernofSoul/TavernofSoul/ktos.pid
# Socket settings
socket = /home/ubuntu/TavernofSoul/TavernofSoul/TavernofSoul/ktos.sock
chmod-socket = 666
uid = www-data
gid = www-data

# Logging
logto = /var/log/TavernofSoul/ktos/ktos.log
touch-logreopen = /home/ubuntu/TavernofSoul/TavernofSoul/TavernofSoul/.touch_to_rotate
unique-cron = 0 0 -1 -1 -1 sh -c 'mv /var/log/TavernofSoul/ktos/ktos.log /var/log/TavernofSoul/ktos/ktos-$(date -d "yesterday" +%Y-%m-%d).log && touch /home/ubuntu/TavernofSoul/TavernofSoul/TavernofSoul/.touch_to_rotate'
unique-cron = 0 0 -1 -1 -1 sh -c 'mv /var/log/TavernofSoul/ktos/ktos.log /var/log/TavernofSoul/ktos/ktos-$(date -d "yesterday" +%Y-%m-%d).log && touch /home/ubuntu/TavernofSoul/TavernofSoul/TavernofSoul/.touch_to_rotate && find /var/log/TavernofSoul/ktos/ -name "ktos-*.log" -mtime +30 -delete'