"""
Django settings for TavernofSoul project with Cloudflare D1 database.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m+(03apos8*-mlw+ob@x&t&5r2d8%z=n23lyf62xc!^$d^%i53'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
REGION = 'ktos'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Dashboard.apps.DashboardConfig',
    'Jobs.apps.JobsConfig',
    'Skills.apps.SkillsConfig',
    'Attributes.apps.AttributesConfig',
    'Buffs.apps.BuffsConfig',
    'Items.apps.ItemsConfig',
    'ipfparser.apps.IpfparserConfig',
    'Monsters.apps.MonstersConfig',
    'Maps.apps.MapsConfig',
    'Planner.apps.PlannerConfig',
    'Challenge.apps.ChallengeConfig',
    'django.contrib.humanize',
    'Other.apps.OtherConfig',        
    'django.contrib.sitemaps',
    'rest_framework',  # Django REST Framework
    # 'django_prometheus'  # D1에서는 비활성화
]

MIDDLEWARE = [
    # 'django_prometheus.middleware.PrometheusBeforeMiddleware',  # D1에서는 비활성화
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_prometheus.middleware.PrometheusAfterMiddleware'  # D1에서는 비활성화
]

ROOT_URLCONF = 'TavernofSoul.urls'

#PROMETHEUS_METRICS_EXPORT_PORT = 8003  # ktos용 포트
#PROMETHEUS_METRICS_EXPORT_ADDRESS = '0.0.0.0'  # 모든 인터페이스에서 수신

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TavernofSoul.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Cloudflare D1 데이터베이스 설정 - 쓰기 전용
# D1은 SQLite 기반의 서버리스 데이터베이스입니다
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_ktos_d1.sqlite3',
        'OPTIONS': {
            'timeout': 20,
            'isolation_level': None,  # 자동 커밋 모드
        }
    }
}

# Cloudflare D1 API 연결 설정
CLOUDFLARE_ACCOUNT_ID = os.getenv('CLOUDFLARE_ACCOUNT_ID')
CLOUDFLARE_API_TOKEN = os.getenv('CLOUDFLARE_API_TOKEN')
CLOUDFLARE_D1_DATABASE_ID = os.getenv('CLOUDFLARE_D1_DATABASE_ID')

# Cloudflare D1 API를 사용하는 경우
if all([CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_API_TOKEN, CLOUDFLARE_D1_DATABASE_ID]):
    # D1 API 연결 모드
    USE_CLOUDFLARE_D1_API = True
    print("🌐 Cloudflare D1 API 모드 활성화")
else:
    # 로컬 SQLite 모드 (기본)
    USE_CLOUDFLARE_D1_API = False
    print("💻 로컬 SQLite 모드 (개발용)")

# Cloudflare Workers 환경에서 D1 바인딩을 사용하는 경우 (Workers 내부)
if os.getenv('CLOUDFLARE_D1_DATABASE_URL'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('CLOUDFLARE_D1_DATABASE_URL'),
            'OPTIONS': {
                'timeout': 20,
                'isolation_level': None,  # 자동 커밋 모드
            }
        }
    }

# D1 쓰기 전용 최적화 설정
DATABASE_ROUTERS = []

# D1 쓰기 전용을 위한 설정 (SQLite용으로 수정)
# DATABASES['default']['OPTIONS'].update({
#     'init_command': "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
#     'charset': 'utf8mb4',
# })

# 자동 마이그레이션 설정 (기본 마이그레이션 사용)
# MIGRATION_MODULES = {
#     'Dashboard': 'Dashboard.migrations_d1',
#     'Jobs': 'Jobs.migrations_d1',
#     'Skills': 'Skills.migrations_d1',
#     'Attributes': 'Attributes.migrations_d1',
#     'Buffs': 'Buffs.migrations_d1',
#     'Items': 'Items.migrations_d1',
#     'ipfparser': 'ipfparser.migrations_d1',
#     'Monsters': 'Monsters.migrations_d1',
#     'Maps': 'Maps.migrations_d1',
#     'Planner': 'Planner.migrations_d1',
#     'Challenge': 'Challenge.migrations_d1',
#     'Other': 'Other.migrations_d1',
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Cache 설정 - D1 환경에 맞게 조정
# https://docs.djangoproject.com/en/3.2/topics/cache/
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

# Cloudflare KV를 사용한 캐시 설정 (선택사항)
if os.getenv('CLOUDFLARE_KV_NAMESPACE'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = 'static/'
# Static asset configuration
STATIC_ROOT = BASE_DIR / 'staticfiles_ktos_d1'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Cloudflare D1용 JSON 루트 설정
JSON_ROOT = BASE_DIR / "JSON_ktos_d1"

# D1 쓰기 전용 데이터베이스 설정
# 테이블 자동 생성 및 쓰기 전용 최적화
AUTO_CREATE_TABLES = True  # 테이블 자동 생성 플래그

# D1 쓰기 전용을 위한 데이터베이스 설정 (간소화)
# SQLite PRAGMA 설정은 별도로 처리
# DATABASES['default']['OPTIONS'].update({
#     'PRAGMA': [
#         'journal_mode=WAL',
#         'synchronous=NORMAL', 
#         'cache_size=10000',
#         'temp_store=MEMORY',
#         'mmap_size=268435456',  # 256MB
#     ]
# })

# 쓰기 전용 모드 설정
DATABASE_WRITE_ONLY = True

# 자동 마이그레이션 실행 설정
AUTO_MIGRATE = True

# D1 최적화를 위한 추가 설정
DATABASES['default']['CONN_MAX_AGE'] = 0  # 연결 풀링 비활성화
DATABASES['default']['ATOMIC_REQUESTS'] = False  # 원자적 요청 비활성화

# Cloudflare Workers 환경을 위한 추가 설정
if os.getenv('CLOUDFLARE_WORKERS'):
    # Workers 환경에서는 일부 Django 기능이 제한될 수 있습니다
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'
    
    # Workers 환경에서의 보안 설정
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_CF_VISITOR', '{"scheme":"https"}')
    
    # Cloudflare의 IP 범위를 신뢰할 수 있는 프록시로 설정
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

# Django REST Framework 설정
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # 브라우저에서 API 테스트 가능
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 필요에 따라 IsAuthenticated 등으로 변경 가능
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# D1 쓰기 전용 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'd1_write_handler': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'd1_write.log',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['d1_write_handler'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
