# Generated by Django 4.2.11 on 2024-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0012_alter_skills_is_riding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='is_riding',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Buff_Skill',
        ),
    ]
