# Generated by Django 4.2.11 on 2024-04-12 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0022_equipments_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Recipe_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_equipment', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='eq_reinf',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='eq_tc',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Goddess_Reinforce_Chance',
        ),
        migrations.RemoveField(
            model_name='goddess_reinforce_mat',
            name='mat',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='model',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='target',
        ),
        migrations.AddField(
            model_name='equipments',
            name='anvil_atk',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=410, null=True, size=41),
        ),
        migrations.AddField(
            model_name='equipments',
            name='anvil_def',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=410, null=True, size=41),
        ),
        migrations.AddField(
            model_name='equipments',
            name='anvil_price',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=410, null=True, size=41),
        ),
        migrations.AddField(
            model_name='equipments',
            name='transcend_price',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=django.utils.timezone.now, max_length=30, size=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus5',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus6',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_set',
            name='bonus7',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Eq_Reinf',
        ),
        migrations.DeleteModel(
            name='Eq_TC',
        ),
        migrations.DeleteModel(
            name='Goddess_Reinforce_Mat',
        ),
        migrations.AddField(
            model_name='item_recipe_target',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.recipes', verbose_name='recipe'),
        ),
        migrations.AddField(
            model_name='item_recipe_target',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items', verbose_name='target'),
        ),
    ]
