# Generated by Django 4.1.13 on 2026-07-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0023_item_recipe_target_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='package_contents',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
