# Generated by Django 4.1.13 on 2026-10-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0024_items_package_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoddessReinforcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('step', models.PositiveSmallIntegerField()),
                ('chance', models.PositiveIntegerField()),
                ('source', models.TextField()),
                ('materials', models.TextField()),
            ],
            options={
                'ordering': ('level', 'step'),
            },
        ),
        migrations.AddField(
            model_name='equipments',
            name='reinforcement_group',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='equipments',
            name='reinforcement_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gems',
            name='socket_bonuses',
            field=models.TextField(default='{}'),
        ),
        migrations.AddConstraint(
            model_name='goddessreinforcement',
            constraint=models.UniqueConstraint(fields=('level', 'step'), name='goddess_level_step'),
        ),
    ]
