# Generated by Django 4.2.11 on 2024-04-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_jobs_vaivora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='vaivora',
        ),
    ]
